const LENGTH_CONSTANTS = {
  MAX_LENGTH_INPUT: 256,
  DEFAULT_PAGE_SIZE: 10,
  DEFAULT_PAGE: 1,
  MIN_VALUE: 1e-8,
  DEFAULT_TOTAL: 0,
  DEFAULT_NFT_SIZE: 12,
  DEFAULT_NFT_SIZE_MOBILE: 10,
  MAX_LENGTH_DESCRIPTION: 320,
  DEFAULT_PAGE_SIZE_OPTIONS: ['10', '20', '50'],
};

export default LENGTH_CONSTANTS;
