# OUTPUT_LANG_INDEX start from 0
generator-localization:
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=3 SPREADSHEET_ID=1SYTJ2tV4-KSID2eaEWYRlyHVPNnwRbD6bN03gkkcEgw GID_ID=user OUTPUT_FOLDER=../public/locales/en/common.json
	
